name: Playwright Tests Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm ci

      - name: Install Playwright browsers
        run: |
          cd backend
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd backend
          npx playwright test tests/generated --reporter=html

      - name: Upload Playwright HTML report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: backend/playwright-report
          retention-days: 7
